version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: Cbot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: Cbot
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    container_name: Cbot-php-fpm
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  webserver:
    image: nginx:alpine
    container_name: Cbot-webserver
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - php-fpm
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: Cbot-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: homestead
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: always

  node:
    image: node:19
    container_name: Cbot-node
    working_dir: /var/www
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    restart: always



volumes:
  mysql-data:
